ASP.Net/MVC-SIS/MVC_SIS/Models/Data/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Exercises.Models.Data
{
    public class Student
    {
        public int StudentId { get; set; }

        [Required(ErrorMessage = "Please enter first name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter last name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter GPA")]
        [Range(0,4.0,ErrorMessage ="Please enter GPA between(0-4)")]
        public Nullable<decimal> GPA { get; set; }

        public Address Address { get; set; }
        public Major Major { get; set; }
        public List<Course> Courses { get; set; }
    }
}

ASP.Net/MVC-SIS/MVC_SIS/Controllers/AdminController.cs
using Exercises.Models.Data;
using Exercises.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Exercises.Controllers
{
    public class AdminController : Controller
    {

        [HttpGet]
        public ActionResult Majors()
        {
            var model = MajorRepository.GetAll();
            return View(model.ToList());
        }

        [HttpGet]
        public ActionResult AddMajor()
        {
            return View(new Major());
        }

        [HttpPost]
        public ActionResult AddMajor(Major major)
        {
            if (string.IsNullOrEmpty(major.MajorName))
            {
                ModelState.AddModelError("MajorName", "Please enter major name");
            }
            if (ModelState.IsValid)
            {
                MajorRepository.Add(major.MajorName);
                return RedirectToAction("Majors");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult EditMajor(int id)
        {
            var major = MajorRepository.Get(id);
            return View(major);
        }

        [HttpPost]
        public ActionResult EditMajor(Major major)
        {
            if (string.IsNullOrEmpty(major.MajorName))
            {
                ModelState.AddModelError("MajorName","Please enter major name");
            }
            if (ModelState.IsValid)
            {
                MajorRepository.Edit(major);
                return RedirectToAction("Majors");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult DeleteMajor(int id)
        {
            var major = MajorRepository.Get(id);
            return View(major);
        }

        [HttpPost]
        public ActionResult DeleteMajor(Major major)
        {
            MajorRepository.Delete(major.MajorId);
            return RedirectToAction("Majors");
        }

        // Methods for States
        [HttpGet]
        public ActionResult States()
        {
            var model = StateRepository.GetAll();
            return View(model.ToList());
        }
        [HttpGet]
        public ActionResult AddState()
        {
            return View(new State());
        }

        [HttpPost]
        public ActionResult AddState(State state)
        {
            if (string.IsNullOrEmpty(state.StateAbbreviation))
            {
                ModelState.AddModelError("StateAbbreviation","Please enter state abbreviation");
            }
            if (string.IsNullOrEmpty(state.StateName))
            {
                ModelState.AddModelError("StateName","Please enter state name");
            }

            if (ModelState.IsValid)
            {
                StateRepository.Add(state);
                return RedirectToAction("States");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult EditState(string stateAbbreviation)
        {
            var state = StateRepository.Get(stateAbbreviation);
            return View(state);
        }

        [HttpPost]
        public ActionResult EditState(State state)
        {
            if (string.IsNullOrEmpty(state.StateAbbreviation))
            {
                ModelState.AddModelError("StateAbbreviation",
                    "Please enter state abbreviation");
            }

            if (string.IsNullOrEmpty(state.StateName))
            {
                ModelState.AddModelError("StateName",
                    "Please enter state name");
            }

            if (ModelState.IsValid)
            {
                // here we would save the appointment to a database
                StateRepository.Edit(state);
                return RedirectToAction("States");
            }
            else
            {
                // send them back to the entry form
                return View(state);
            }
        }

        [HttpGet]
        public ActionResult DeleteState(string stateAbbreviation)
        {
            var state = StateRepository.Get(stateAbbreviation);
            return View(state);
        }

        [HttpPost]
        public ActionResult DeleteState(State state)
        {
            StateRepository.Delete(state.StateAbbreviation);
            return RedirectToAction("States");
        }

        /// <summary>
        /// Course Actions
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Courses()
        {
            var model = CourseRepository.GetAll();
            return View(model.ToList());
        }
        [HttpGet]
        public ActionResult AddCourse()
        {
            return View(new Course());
        }

        [HttpPost]
        public ActionResult AddCourse(string courseName)
        {
            if (string.IsNullOrEmpty(courseName))
            {
                ModelState.AddModelError("CourseName",
                    "Please enter course name");
            }

            if (ModelState.IsValid)
            {
                // here we would save the appointment to a database
                CourseRepository.Add(courseName);
                return RedirectToAction("Courses");
            }
            else
            {
                // send them back to the entry form
                return View();
            }
        }

        [HttpGet]
        public ActionResult EditCourse(int courseId)
        {
            var course = CourseRepository.Get(courseId);
            return View(course);
        }

        [HttpPost]
        public ActionResult EditCourse(Course course)
        {
            if (string.IsNullOrEmpty(course.CourseName))
            {
                ModelState.AddModelError("CourseName","Please enter course name");
            }
            if (ModelState.IsValid)
            {
                CourseRepository.Edit(course);
                return RedirectToAction("Courses");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult DeleteCourse(int courseId)
        {
            var course = CourseRepository.Get(courseId);
            return View(course);
        }

        [HttpPost]
        public ActionResult DeleteCourse(Course course)
        {
            CourseRepository.Delete(course.CourseId);
            return RedirectToAction("Courses");
        }
    }
}

ASP.Net/MVC-SIS/MVC_SIS/Controllers/StudentController.cs
using Exercises.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Exercises.Models.Data;
using Exercises.Models.ViewModels;

namespace Exercises.Controllers
{
    public class StudentController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult List()
        {
            var model = StudentRepository.GetAll();

            return View(model);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var viewModel = new StudentVM();
            viewModel.SetCourseItems(CourseRepository.GetAll());
            viewModel.SetMajorItems(MajorRepository.GetAll());
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Add(StudentVM studentVM)
        {
            //ModelState.Clear();
            //if (string.IsNullOrEmpty(studentVM.Student.FirstName))
            //{
            //    ModelState.AddModelError("FirstName","Please enter first name");
            //}
            //if (string.IsNullOrEmpty(studentVM.Student.LastName))
            //{
            //    ModelState.AddModelError("LastName", "Please enter last name");
            //}
            //if (string.IsNullOrEmpty(studentVM.Student.GPA.ToString()))
            //{
            //    ModelState.AddModelError("GPA","Please enter GPA");
            //}
            //if (string.IsNullOrEmpty(studentVM.Student.Major.MajorId.ToString()) || studentVM.Student.Major.MajorId == 0)
            //{
            //    ModelState.AddModelError("MajorId", "Please select major");
            //}
            //if (studentVM.SelectedCourseIds.Count <= 0)
            //{
            //    ModelState.AddModelError("SelectedCourseIds", "Please select Courses");
            //}

            if (ModelState.IsValid)
            {
                studentVM.Student.Courses = new List<Course>();

                foreach (var id in studentVM.SelectedCourseIds)
                    studentVM.Student.Courses.Add(CourseRepository.Get(id));

                studentVM.Student.Major = MajorRepository.Get(studentVM.Student.Major.MajorId);

                StudentRepository.Add(studentVM.Student);

                return RedirectToAction("List");
            }
            else
            {
                studentVM.SetCourseItems(CourseRepository.GetAll());
                studentVM.SetMajorItems(MajorRepository.GetAll());
               
                return View(studentVM);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var student = StudentRepository.Get(id);
            var studentVM = new StudentVM();
            studentVM.Student = student;
            studentVM.SetCourseItems(CourseRepository.GetAll());
            if (student.Courses!=null)
            {
                studentVM.SelectedCourseIds = (from course in student.Courses
                                               select course.CourseId).ToList();
            }
            studentVM.Student.Major = student.Major; 
            studentVM.SetMajorItems(MajorRepository.GetAll());
            studentVM.SetStateItems(StateRepository.GetAll());

            return View(studentVM);
        }


        [HttpPost]
        public ActionResult Edit(StudentVM studentVM)
        {
            if (ModelState.IsValid)
            {
                studentVM.Student.Courses = new List<Course>();

                foreach (var id in studentVM.SelectedCourseIds)
                    studentVM.Student.Courses.Add(CourseRepository.Get(id));

                studentVM.Student.Major = MajorRepository.Get(studentVM.Student.Major.MajorId);

                StudentRepository.Edit(studentVM.Student);
                return RedirectToAction("List");
            }
            else
            {
                studentVM.SetCourseItems(CourseRepository.GetAll());
                studentVM.SetMajorItems(MajorRepository.GetAll());
                return View(studentVM);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var student = StudentRepository.Get(id);
            return View(student);
        }

        [HttpPost]
        public ActionResult Delete(Student student)
        {
            StudentRepository.Delete(student.StudentId);
            return RedirectToAction("List");
        }
    }
}

ASP.Net/MVC-SIS/MVC_SIS/Views/Student/Add.cshtml
@model Exercises.Models.ViewModels.StudentVM

@{
    ViewBag.Title = "Student-Add";
}

<div class="row">
    <div class="col-xs-12 col-sm-3">
        @Html.Partial("StudentNav")
    </div>

    <div class="col-xs-12 col-sm-9">
        <h3>Add Student</h3>

        @*@Html.ValidationSummary()*@

        @using (Html.BeginForm("Add", "Student", FormMethod.Post, new { @class = "addStudentForm" }))
        {
            <div class="col-xs-12 col-sm-7">
                <ul class="list-group" id="errorMessages"></ul>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h4 class="panel-title">Personal Details</h4>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <label>First Name:</label>
                            @Html.TextBoxFor(m => m.Student.FirstName, new { @class = "form-control", id = "txt-firstName", placeholder = "First Name" })
                            <span class="text-danger">@Html.ValidationMessageFor(s => s.Student.FirstName)</span>
                        </div>
                        <div class="form-group">
                            <label>Last Name:</label>
                            @Html.TextBoxFor(m => m.Student.LastName, new { @class = "form-control", id = "txt-lastName", placeholder = "Last Name" })
                            <span class="text-danger">@Html.ValidationMessageFor(s => s.Student.LastName)</span>
                        </div>
                        <div class="form-group">
                            <label>Major:</label>
                            @Html.DropDownListFor(m => m.Student.Major.MajorId, Model.MajorItems, "-Choose One-", new { @class = "form-control", id = "list-major" })
                            <span class="text-danger">@Html.ValidationMessageFor(s => s.Student.Major.MajorId)</span>
                        </div>
                        <div class="form-group">
                            <label>GPA:</label>
                            @Html.TextBoxFor(m => m.Student.GPA, new { @class = "form-control", type = "number", id = "txt-GPA", step = "any", placeholder = "GPA" })
                            <span class="text-danger">@Html.ValidationMessageFor(s => s.Student.GPA)</span>
                        </div>
                        <h4>Courses</h4>
                        <div class="form-group">
                            @Html.ListBoxFor(m => m.SelectedCourseIds, Model.CourseItems, new { @class = "form-control", id = "list-courseId" })
                            <span class="text-danger">@Html.ValidationMessageFor(s => s.SelectedCourseIds)</span>
                        </div>
                        <button class="btn btn-primary" id="studentAdd" onclick="return validateStudent();">Save</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

ASP.Net/MVC-SIS/MVC_SIS/Views/Student/Delete.cshtml
@model Exercises.Models.Data.Student

@{
    ViewBag.Title = "Student-Delete";
}

<div class="row">
    <div class="col-xs-12 col-sm-3">
        <h4>Student Information</h4>
    </div>
    <div class="col-xs-12 col-sm-9">
        <h4>Delete Student</h4>
        @Html.ActionLink("Return to List", "List", "Student")
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(s => s.StudentId)
            <p>Are you sure that you wish to delete the student <b>@Html.DisplayFor(s =>s.FirstName)</b>?</p>
            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
            @Html.ActionLink("Cancel", "List", "Student", null, new { @class = "btn btn-sm btn-info" })
        }
    </div>
</div>

ASP.Net/MVC-SIS/MVC_SIS/Views/Student/Edit.cshtml
@model Exercises.Models.ViewModels.StudentVM

@{
    ViewBag.Title = "Student-Edit";
}

<div class="row">
    <div class="col-xs-12 col-sm-3">
        @Html.Partial("StudentNav")
    </div>

    <div class="col-xs-12 col-sm-9">
        <h4>Edit Student</h4>
        @*@Html.ValidationSummary()*@

        @*@Html.ActionLink("Return to List", "Student", "Admin")*@

        @using (Html.BeginForm())
        {
            <div class="row">
                <div class="col-xs-12 col-sm-6">
                    <ul class="list-group" id="errorMessages"></ul>
                    @Html.HiddenFor(s => s.Student.StudentId)
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h4 class="panel-title">Personal Details</h4>
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                <label>First Name:</label>
                                @Html.TextBoxFor(m => m.Student.FirstName, new { @class = "form-control", id = "txt-firstName", placeholder = "First Name" })
                                <span class="text-danger">@Html.ValidationMessageFor(s => s.Student.FirstName)</span>
                            </div>
                            <div class="form-group">
                                <label>Last Name:</label>
                                @Html.TextBoxFor(m => m.Student.LastName, new { @class = "form-control", id = "txt-lastName", placeholder = "Last Name" })
                                <span class="text-danger">@Html.ValidationMessageFor(s => s.Student.LastName)</span>
                            </div>
                            <div class="form-group">
                                <label>Major:</label>
                                @Html.DropDownListFor(m => m.Student.Major.MajorId, Model.MajorItems, "-Choose One-", new { @class = "form-control", id = "list-major" })
                                <span class="text-danger">@Html.ValidationMessageFor(s => s.Student.Major.MajorId)</span>
                            </div>
                            <div class="form-group">
                                <label>GPA:</label>
                                @Html.TextBoxFor(m => m.Student.GPA, new { @class = "form-control", type = "number", id = "txt-GPA", step = "any" })
                                <span class="text-danger">@Html.ValidationMessageFor(s => s.Student.GPA)</span>
                            </div>
                            <h4>Courses</h4>
                            <div class="form-group">
                                @Html.ListBoxFor(m => m.SelectedCourseIds, Model.CourseItems, new { @class = "form-control", id = "list-courseId" })
                                <span class="text-danger">@Html.ValidationMessageFor(s => s.SelectedCourseIds)</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-3">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <h4 class="panel-title">Address</h4>
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                <label>Street1:</label>
                                @Html.TextBoxFor(m => m.Student.Address.Street1, new { @class = "form-control", placeholder = "Street1" })
                                <span class="text-danger">@Html.ValidationMessageFor(s => s.Student.Address.Street1)</span>
                            </div>
                            <div class="form-group">
                                <label>Street2:</label>
                                @Html.TextBoxFor(m => m.Student.Address.Street2, new { @class = "form-control", placeholder = "Street2" })
                                <span class="text-danger">@Html.ValidationMessageFor(s => s.Student.Address.Street2)</span>
                            </div>
                            <div class="form-group">
                                <label>City:</label>
                                @Html.TextBoxFor(m => m.Student.Address.City, new { @class = "form-control", placeholder = "City" })
                                <span class="text-danger">@Html.ValidationMessageFor(s => s.Student.Address.City)</span>
                            </div>
                            <div class="form-group">
                                <label>State:</label>
                                @Html.TextBoxFor(m => m.Student.Address.State.StateAbbreviation, new { @class = "form-control", placeholder = "StateAbbreviation" })
                                <span class="text-danger">@Html.ValidationMessageFor(s => s.Student.Address.State.StateAbbreviation)</span>
                                @Html.TextBoxFor(m => m.Student.Address.State.StateName, new { @class = "form-control", placeholder = "State Name" })
                                <span class="text-danger">@Html.ValidationMessageFor(s => s.Student.Address.State.StateName)</span>
                            </div>
                            <div class="form-group">
                                <label>Postal Code:</label>
                                @Html.TextBoxFor(m => m.Student.Address.PostalCode, new { @class = "form-control", placeholder = "Postal Code" })
                                <span class="text-danger">@Html.ValidationMessageFor(s => s.Student.Address.PostalCode)</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-6 justify-content-sm-center">
                    @Html.ActionLink("Cancel", "List", "Student", null, new { @class = "btn btn-sm btn-primary" })
                </div>
                <div class="col-sm-6 justify-content-sm-center">
                    <button type="submit" class="btn btn-sm btn-primary" onclick="return validateStudent();">Save</button>
                </div>
            </div>
        }
    </div>
</div>

ASP.Net/MVC-SIS/MVC_SIS/Views/Student/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-xs-12 col-sm-3">
        @Html.Partial("StudentNav")
    </div>
    <div class="col-xs-12 col-sm-9">
        <p>
            This is the student area of the web site.  We can list, add, edit, and delete student information here.
        </p>
    </div>
</div>

ASP.Net/MVC-SIS/MVC_SIS/Views/Student/List.cshtml
@model IEnumerable<Exercises.Models.Data.Student>

@{
    ViewBag.Title = "List";
}

<div class="row">
    <div class="col-xs-12 col-sm-3">
        @Html.Partial("StudentNav")
    </div>
    <div class="col-xs-12 col-sm-9">
        <div class="row">
            <div class="col-xs-12">
                <h4>Student List</h4>
                <p>@Html.ActionLink("Add a Student", "Add", "Student", null, new { @class = "btn btn-primary" })</p>
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Major</th>
                            <th>GPA</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var student in Model)
                        {
                            <tr>
                                <td>@student.FirstName</td>
                                <td>@student.LastName</td>
                                <td>@student.Major.MajorName</td>
                                <td>@student.GPA</td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", "Student", new { id = student.StudentId },null) |
                                    @Html.ActionLink("Delete", "Delete", "Student", new { id = student.StudentId },null)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>